### ISSUE TITLE
Options screen does not get populated on testnet

### ISSUE THREAD

**Issue by way2rach** [shrub-finance/shrub-finance#124]
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/10775165/131732155-07ff2727-796d-4598-8775-446d16397c4f.png">

**Comment by jguthrie7** [comment]
TODO:

- go through all of the event scanning methods
- Restrict max search blocks to 1000
- Use contract deploy blockHeight as a minimum

**Comment by jguthrie7** [comment]
`getMatchedEvents`
`getAnnouncedEvents`
