### ISSUE TITLE
Fix issues with analytics

### ISSUE THREAD

**Issue by way2rach** [shrub-finance/shrub-finance#335]

**Comment by way2rach** [comment]
events are not firing 

we need to make sure react ga is working properly with the reach router
https://medium.com/mobile-web-dev/google-analytics-with-reach-router-in-5-steps-9a1f5246ec0

**Comment by amrindersingh343** [comment]
i will take this

**Comment by amrindersingh343** [comment]
i have pushed the code for this on 6 April
